version: '3.8'

services:
  brrrr-test:
    build: .
    container_name: brrrr-evaluation
    volumes:
      - .:/app
    working_dir: /app
    command: go test -v
    environment:
      - GO111MODULE=on